In [62]:
pip install scikit-learn


Note: you may need to restart the kernel to use updated packages.


In [63]:
import pandas as pd
import numpy as np

In [64]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [65]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [66]:
# def get_spam(x):
#     if x == 'spam':
#         return 1
#     return 0    

In [67]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [68]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [69]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [70]:
X_train.head(10)

2215    Ok then i'll let him noe later n ask him call ...
5555    Yeh. Indians was nice. Tho it did kane me off ...
2934    Yo do you know anyone  &lt;#&gt;  or otherwise...
584     my ex-wife was not able to have kids. Do you w...
754                       When did you get to the library
201                          I sent you  &lt;#&gt;  bucks
536     Good afternoon, my love! How goes that day ? I...
4777    Quite lor. But dun tell him wait he get compla...
2553                          Oh fine, I'll be by tonight
1607          Ok no prob... I'll come after lunch then...
Name: Message, dtype: object

In [71]:
y_train.head(10)

2215    0
5555    0
2934    0
584     0
754     0
201     0
536     0
4777    0
2553    0
1607    0
Name: spam, dtype: int64

### Create bag of words representation using CountVectorizer

In [72]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

x_train_cv = v.fit_transform(X_train.values)
x_train_cv
# as it give spasse matrix so convert it into array

<4457x7807 sparse matrix of type '<class 'numpy.int64'>'
	with 59177 stored elements in Compressed Sparse Row format>

In [73]:
# convert to array
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [74]:
x_train_cv.toarray()[:2][0]
# firt two samples and col 0 

array([0, 0, 0, ..., 0, 0, 0])

In [75]:
x_train_cv.shape

(4457, 7807)

In [76]:
# these are function of bog
dir(v)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_default_requests',
 '_get_metadata_request',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_stop_words_id',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',

In [77]:
v.vocabulary_
# how many each word

{'ok': 4935,
 'then': 6867,
 'll': 4176,
 'let': 4100,
 'him': 3446,
 'noe': 4816,
 'later': 4040,
 'ask': 1101,
 'call': 1625,
 'tmr': 6969,
 'yeh': 7743,
 'indians': 3672,
 'was': 7443,
 'nice': 4789,
 'tho': 6900,
 'it': 3766,
 'did': 2312,
 'kane': 3902,
 'me': 4422,
 'off': 4914,
 'bit': 1385,
 'he': 3378,
 'we': 7470,
 'shud': 6170,
 'go': 3173,
 'out': 5031,
 'drink': 2461,
 'sometime': 6339,
 'soon': 6353,
 'mite': 4535,
 'hav': 3366,
 'da': 2155,
 'works': 7658,
 'laugh': 4043,
 'love': 4242,
 'pete': 5194,
 'yo': 7761,
 'do': 2380,
 'you': 7765,
 'know': 3968,
 'anyone': 1009,
 'lt': 4262,
 'gt': 3272,
 'or': 4996,
 'otherwise': 5024,
 'able': 770,
 'to': 6974,
 'buy': 1600,
 'liquor': 4155,
 'our': 5029,
 'guy': 3294,
 'flaked': 2895,
 'and': 976,
 'right': 5809,
 'now': 4861,
 'if': 3607,
 'don': 2413,
 'get': 3128,
 'hold': 3474,
 'of': 4913,
 'somebody': 6330,
 'its': 3772,
 'just': 3882,
 'loko': 4199,
 'all': 926,
 'night': 4796,
 'my': 4679,
 'ex': 2702,
 'wife': 7568,

In [78]:
# this all unique words are present like in copy you have 
v.get_feature_names_out()

array(['00', '000', '008704050406', ..., 'èn', 'ú1', '〨ud'], dtype=object)

In [99]:
v.get_feature_names_out()[1101]

'ask'

In [80]:
# now convert train to numpy array
X_train_np = x_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [81]:
# FIND WHRE X_train_np IS NOT 0 THAT IS HAM 1 MEANS SPAM
np.where(X_train_np[0]!=0)

(array([1101, 1625, 3446, 4040, 4100, 4176, 4816, 4935, 6867, 6969]),)

In [94]:
X_train[1:4]

5555    Yeh. Indians was nice. Tho it did kane me off ...
2934    Yo do you know anyone  &lt;#&gt;  or otherwise...
584     my ex-wife was not able to have kids. Do you w...
Name: Message, dtype: object

In [88]:
# X_train[0][1771]

In [98]:
X_train_np[0][1101]

1

### Train the naive bayes model

In [101]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(x_train_cv, y_train)

MultinomialNB()

In [102]:
# fit it as all input in word form so convert it vector
X_test_cv = v.transform(X_test)

In [103]:
# Evaluate Performance
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       969
           1       0.98      0.87      0.92       146

    accuracy                           0.98      1115
   macro avg       0.98      0.93      0.95      1115
weighted avg       0.98      0.98      0.98      1115



we use f1 score as imbalace data as number f spam is less as compared to ham
mbalanced Datasets: When you have imbalanced classes in your dataset, where one class significantly outnumbers the other, accuracy alone might not be a good performance measure. In such cases, the F1 score can provide a more balanced assessment by considering both false positives and false negatives.

In [104]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])

first email  ham and second is spam